services:
  orchestra:
    image: ezka77/xen-orchestra-ce:latest
    container_name: XO_server
    cap_add:
      - SYS_ADMIN
    depends_on:
      - redis
    ports:
      - 5050:443
    environment:
      - DEBUG=xo:main
      - NODE_ENV=production
      - XOA_PLAN=5
      - XO_HTTP_REDIRECTTOHTTPS=true
      - XO_HTTP_LISTEN_PORT=80
      - XO_HTTPS_LISTEN_PORT=443
      - XO_HTTPS_LISTEN_AUTOCERT=true
    volumes:
      - xo-data:/storage
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: XO_redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  xo-data:
  redis-data:
